jobs:
  build:
    machine:
      image: 'circleci/classic:edge'
    steps:
      - checkout
      - run:
          name: Heroku
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker build --rm=false -t registry.heroku.com/$APP_NAME/release .
            docker push registry.heroku.com/$APP_NAME/release:latest


