jobs:
  build:
    machine:
      image: 'circleci/classic:edge'
    steps:
      - checkout
      - run:
          name: Build, push and release
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
            docker build --rm=false -t registry.heroku.com/$APP_NAME/web .
            docker push registry.heroku.com/$APP_NAME/web:latest
            WEB_DOCKER_IMAGE_ID="$(docker inspect registry.heroku.com/$APP_NAME/web:latest --format={{.Id}})"
            curl -n -X PATCH https://api.heroku.com/apps/$APP_NAME/formation \
              -d '{
              "updates": [
                {
                  "type": "web",
                  "docker_image": "$WEB_DOCKER_IMAGE_ID"
                }
              ]
            }' \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.heroku+json; version=3.docker-releases"



